//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja_chica
    {
        public int id_caja { get; set; }
        public System.DateTime hora_apertura { get; set; }
        public System.DateTime hora_cierre { get; set; }
        public double monto_apertura { get; set; }
        public double monto_cierre { get; set; }
        public int id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
