//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja_chica
    {
        public int id_caja { get; set; }
        public System.DateTime hora_apertura { get; set; }
        public System.DateTime hora_cierre { get; set; }
        public double monto_apertura { get; set; }
        public double monto_cierre { get; set; }
        public int cod_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
