//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_detalle
    {
        public int id_detalle_factura { get; set; }
        public int id_factura_encabezado { get; set; }
        public int cod_servicio { get; set; }
        public int cantidad { get; set; }
        public double precio_servicio { get; set; }
    
        public virtual factura_encabezado factura_encabezado { get; set; }
        public virtual tipo_servicio tipo_servicio { get; set; }
    }
}
