//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LavaCarEntities : DbContext
    {
        public LavaCarEntities()
            : base("name=LavaCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caja_chica> caja_chica { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<fabricante> fabricantes { get; set; }
        public virtual DbSet<factura_detalle> factura_detalle { get; set; }
        public virtual DbSet<factura_encabezado> factura_encabezado { get; set; }
        public virtual DbSet<marca_vehiculo> marca_vehiculo { get; set; }
        public virtual DbSet<modelo_vehiculo> modelo_vehiculo { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<tipo_servicio> tipo_servicio { get; set; }
        public virtual DbSet<tipo_vehiculo> tipo_vehiculo { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<vehiculo> vehiculos { get; set; }
        public virtual DbSet<vehiculos_x_cliente> vehiculos_x_cliente { get; set; }
    
        public virtual int InsertaNuevoModelo(string nombre_modelo, Nullable<int> id_marca_modelo)
        {
            var nombre_modeloParameter = nombre_modelo != null ?
                new ObjectParameter("nombre_modelo", nombre_modelo) :
                new ObjectParameter("nombre_modelo", typeof(string));
    
            var id_marca_modeloParameter = id_marca_modelo.HasValue ?
                new ObjectParameter("id_marca_modelo", id_marca_modelo) :
                new ObjectParameter("id_marca_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaNuevoModelo", nombre_modeloParameter, id_marca_modeloParameter);
        }
    
        public virtual ObjectResult<Retorna_Cierres_Caja_Result> Retorna_Cierres_Caja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Retorna_Cierres_Caja_Result>("Retorna_Cierres_Caja");
        }
    
        public virtual ObjectResult<RetornaCantones_Result> RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantones_Result>("RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<RetornaUsuario_Result> RetornaUsuario(string correoElectronico, string nombreCompleto, Nullable<int> id_Usuario)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("correoElectronico", correoElectronico) :
                new ObjectParameter("correoElectronico", typeof(string));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuario_Result>("RetornaUsuario", correoElectronicoParameter, nombreCompletoParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<RetornaUsuarioCorreoPwd_Result> RetornaUsuarioCorreoPwd(string correoElectronico, string contrasena)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("correoElectronico", correoElectronico) :
                new ObjectParameter("correoElectronico", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioCorreoPwd_Result>("RetornaUsuarioCorreoPwd", correoElectronicoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<RetornaUsuarioID_Result> RetornaUsuarioID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioID_Result>("RetornaUsuarioID", id_UsuarioParameter);
        }
    
        public virtual int sp_AnularFactura(Nullable<int> id_Factura)
        {
            var id_FacturaParameter = id_Factura.HasValue ?
                new ObjectParameter("id_Factura", id_Factura) :
                new ObjectParameter("id_Factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AnularFactura", id_FacturaParameter);
        }
    
        public virtual int sp_AperturaCaja(Nullable<double> monto_apertura, Nullable<int> id_usuarioapertura)
        {
            var monto_aperturaParameter = monto_apertura.HasValue ?
                new ObjectParameter("monto_apertura", monto_apertura) :
                new ObjectParameter("monto_apertura", typeof(double));
    
            var id_usuarioaperturaParameter = id_usuarioapertura.HasValue ?
                new ObjectParameter("id_usuarioapertura", id_usuarioapertura) :
                new ObjectParameter("id_usuarioapertura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AperturaCaja", monto_aperturaParameter, id_usuarioaperturaParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_Cierra_Caja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_Cierra_Caja");
        }
    
        public virtual int sp_Cierre_Caja(Nullable<int> id_usuariocierre)
        {
            var id_usuariocierreParameter = id_usuariocierre.HasValue ?
                new ObjectParameter("id_usuariocierre", id_usuariocierre) :
                new ObjectParameter("id_usuariocierre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Cierre_Caja", id_usuariocierreParameter);
        }
    
        public virtual ObjectResult<sp_cierre_cajas_Result> sp_cierre_cajas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cierre_cajas_Result>("sp_cierre_cajas");
        }
    
        public virtual int sp_Elimina_Fabricante(Nullable<int> id_fabricante)
        {
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Fabricante", id_fabricanteParameter);
        }
    
        public virtual int sp_Elimina_Modelo(Nullable<int> id_modelo)
        {
            var id_modeloParameter = id_modelo.HasValue ?
                new ObjectParameter("id_modelo", id_modelo) :
                new ObjectParameter("id_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Modelo", id_modeloParameter);
        }
    
        public virtual int sp_Elimina_TipoVehiculo(Nullable<int> id_tipo_vehiculo)
        {
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_TipoVehiculo", id_tipo_vehiculoParameter);
        }
    
        public virtual int sp_Elimina_Vehiculos_x_Cliente(Nullable<int> id_vehiculo_cliente)
        {
            var id_vehiculo_clienteParameter = id_vehiculo_cliente.HasValue ?
                new ObjectParameter("id_vehiculo_cliente", id_vehiculo_cliente) :
                new ObjectParameter("id_vehiculo_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Vehiculos_x_Cliente", id_vehiculo_clienteParameter);
        }
    
        public virtual int sp_EliminaCanton(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCanton", id_CantonParameter);
        }
    
        public virtual int sp_EliminaCliente(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCliente", id_clienteParameter);
        }
    
        public virtual int sp_EliminaMarca(Nullable<int> id_modelo)
        {
            var id_modeloParameter = id_modelo.HasValue ?
                new ObjectParameter("id_modelo", id_modelo) :
                new ObjectParameter("id_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaMarca", id_modeloParameter);
        }
    
        public virtual int sp_EliminaPais(Nullable<int> id_pais)
        {
            var id_paisParameter = id_pais.HasValue ?
                new ObjectParameter("id_pais", id_pais) :
                new ObjectParameter("id_pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaPais", id_paisParameter);
        }
    
        public virtual int sp_EliminarVehiculo(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarVehiculo", iDParameter);
        }
    
        public virtual int sp_Fabricante_Update(Nullable<int> id_fabricante, string nombre_fabricante, Nullable<int> pais)
        {
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            var nombre_fabricanteParameter = nombre_fabricante != null ?
                new ObjectParameter("nombre_fabricante", nombre_fabricante) :
                new ObjectParameter("nombre_fabricante", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Fabricante_Update", id_fabricanteParameter, nombre_fabricanteParameter, paisParameter);
        }
    
        public virtual int sp_Inserta_Fabricante(string nombre_fabricante, Nullable<int> pais)
        {
            var nombre_fabricanteParameter = nombre_fabricante != null ?
                new ObjectParameter("nombre_fabricante", nombre_fabricante) :
                new ObjectParameter("nombre_fabricante", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Fabricante", nombre_fabricanteParameter, paisParameter);
        }
    
        public virtual int sp_Inserta_factura_Detalle(Nullable<int> id_factura_encabezado, Nullable<int> id_servicio, Nullable<int> cantidad, Nullable<double> precio)
        {
            var id_factura_encabezadoParameter = id_factura_encabezado.HasValue ?
                new ObjectParameter("id_factura_encabezado", id_factura_encabezado) :
                new ObjectParameter("id_factura_encabezado", typeof(int));
    
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_factura_Detalle", id_factura_encabezadoParameter, id_servicioParameter, cantidadParameter, precioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Inserta_factura_encabezado(Nullable<int> id_cliente, Nullable<int> vehiculo_id)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var vehiculo_idParameter = vehiculo_id.HasValue ?
                new ObjectParameter("vehiculo_id", vehiculo_id) :
                new ObjectParameter("vehiculo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Inserta_factura_encabezado", id_clienteParameter, vehiculo_idParameter);
        }
    
        public virtual int sp_Inserta_Modelo(string nombre_modelo, Nullable<int> id_marca_modelo)
        {
            var nombre_modeloParameter = nombre_modelo != null ?
                new ObjectParameter("nombre_modelo", nombre_modelo) :
                new ObjectParameter("nombre_modelo", typeof(string));
    
            var id_marca_modeloParameter = id_marca_modelo.HasValue ?
                new ObjectParameter("id_marca_modelo", id_marca_modelo) :
                new ObjectParameter("id_marca_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Modelo", nombre_modeloParameter, id_marca_modeloParameter);
        }
    
        public virtual int sp_Inserta_parametro(string nombre, string correo_aperture, string correo_cierre, Nullable<double> monto_minimo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correo_apertureParameter = correo_aperture != null ?
                new ObjectParameter("correo_aperture", correo_aperture) :
                new ObjectParameter("correo_aperture", typeof(string));
    
            var correo_cierreParameter = correo_cierre != null ?
                new ObjectParameter("correo_cierre", correo_cierre) :
                new ObjectParameter("correo_cierre", typeof(string));
    
            var monto_minimoParameter = monto_minimo.HasValue ?
                new ObjectParameter("monto_minimo", monto_minimo) :
                new ObjectParameter("monto_minimo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_parametro", nombreParameter, correo_apertureParameter, correo_cierreParameter, monto_minimoParameter);
        }
    
        public virtual int SP_INSERTA_SERVICIO(string nOMBRE_SERVICIO, Nullable<double> pRECIO_SERVICIO)
        {
            var nOMBRE_SERVICIOParameter = nOMBRE_SERVICIO != null ?
                new ObjectParameter("NOMBRE_SERVICIO", nOMBRE_SERVICIO) :
                new ObjectParameter("NOMBRE_SERVICIO", typeof(string));
    
            var pRECIO_SERVICIOParameter = pRECIO_SERVICIO.HasValue ?
                new ObjectParameter("PRECIO_SERVICIO", pRECIO_SERVICIO) :
                new ObjectParameter("PRECIO_SERVICIO", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTA_SERVICIO", nOMBRE_SERVICIOParameter, pRECIO_SERVICIOParameter);
        }
    
        public virtual int sp_Inserta_TipoVehiculo(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_TipoVehiculo", nombreParameter);
        }
    
        public virtual int sp_Inserta_Vehiculo(Nullable<int> placa, Nullable<int> id_marca, Nullable<int> id_fabricante_vehiculo, Nullable<int> id_tipo_vehiculo, Nullable<int> id_modelo_vehiculo, Nullable<short> cantidad_puertas, Nullable<short> cantidad_ruedas, Nullable<System.DateTime> año_fabricacion)
        {
            var placaParameter = placa.HasValue ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(int));
    
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            var id_fabricante_vehiculoParameter = id_fabricante_vehiculo.HasValue ?
                new ObjectParameter("id_fabricante_vehiculo", id_fabricante_vehiculo) :
                new ObjectParameter("id_fabricante_vehiculo", typeof(int));
    
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            var id_modelo_vehiculoParameter = id_modelo_vehiculo.HasValue ?
                new ObjectParameter("id_modelo_vehiculo", id_modelo_vehiculo) :
                new ObjectParameter("id_modelo_vehiculo", typeof(int));
    
            var cantidad_puertasParameter = cantidad_puertas.HasValue ?
                new ObjectParameter("cantidad_puertas", cantidad_puertas) :
                new ObjectParameter("cantidad_puertas", typeof(short));
    
            var cantidad_ruedasParameter = cantidad_ruedas.HasValue ?
                new ObjectParameter("cantidad_ruedas", cantidad_ruedas) :
                new ObjectParameter("cantidad_ruedas", typeof(short));
    
            var año_fabricacionParameter = año_fabricacion.HasValue ?
                new ObjectParameter("año_fabricacion", año_fabricacion) :
                new ObjectParameter("año_fabricacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Vehiculo", placaParameter, id_marcaParameter, id_fabricante_vehiculoParameter, id_tipo_vehiculoParameter, id_modelo_vehiculoParameter, cantidad_puertasParameter, cantidad_ruedasParameter, año_fabricacionParameter);
        }
    
        public virtual int sp_Inserta_Vehiculos_x_Cliente(Nullable<int> id_vehiculo, Nullable<int> id_cliente)
        {
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Vehiculos_x_Cliente", id_vehiculoParameter, id_clienteParameter);
        }
    
        public virtual int sp_InsertaCanton(Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCanton", id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_InsertaMarca(string nombre_marca, Nullable<int> id_fabricante)
        {
            var nombre_marcaParameter = nombre_marca != null ?
                new ObjectParameter("nombre_marca", nombre_marca) :
                new ObjectParameter("nombre_marca", typeof(string));
    
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaMarca", nombre_marcaParameter, id_fabricanteParameter);
        }
    
        public virtual int sp_InsertaNuevoCliente(string nombre, string apellido1, string apellido2, Nullable<int> cedula, Nullable<int> id_provincia, Nullable<int> id_canton, Nullable<int> id_distrito, string direccion, Nullable<int> telefono, string email)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaNuevoCliente", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter, id_provinciaParameter, id_cantonParameter, id_distritoParameter, direccionParameter, telefonoParameter, emailParameter);
        }
    
        public virtual int sp_InsertaPais(string nombrepais)
        {
            var nombrepaisParameter = nombrepais != null ?
                new ObjectParameter("nombrepais", nombrepais) :
                new ObjectParameter("nombrepais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaPais", nombrepaisParameter);
        }
    
        public virtual int sp_Modifica_Fabricante(Nullable<int> id_fabricante, string nombre_fabricante, Nullable<int> pais)
        {
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            var nombre_fabricanteParameter = nombre_fabricante != null ?
                new ObjectParameter("nombre_fabricante", nombre_fabricante) :
                new ObjectParameter("nombre_fabricante", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Fabricante", id_fabricanteParameter, nombre_fabricanteParameter, paisParameter);
        }
    
        public virtual int SP_MODIFICA_SERVICIO(Nullable<int> iD_SERVICIO, string nOMBRE_SERVICIO, Nullable<double> pRECIO_SERVICIO)
        {
            var iD_SERVICIOParameter = iD_SERVICIO.HasValue ?
                new ObjectParameter("ID_SERVICIO", iD_SERVICIO) :
                new ObjectParameter("ID_SERVICIO", typeof(int));
    
            var nOMBRE_SERVICIOParameter = nOMBRE_SERVICIO != null ?
                new ObjectParameter("NOMBRE_SERVICIO", nOMBRE_SERVICIO) :
                new ObjectParameter("NOMBRE_SERVICIO", typeof(string));
    
            var pRECIO_SERVICIOParameter = pRECIO_SERVICIO.HasValue ?
                new ObjectParameter("PRECIO_SERVICIO", pRECIO_SERVICIO) :
                new ObjectParameter("PRECIO_SERVICIO", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICA_SERVICIO", iD_SERVICIOParameter, nOMBRE_SERVICIOParameter, pRECIO_SERVICIOParameter);
        }
    
        public virtual int sp_Modifica_TipoVehiculo(string nombre, Nullable<int> id_tipo_vehiculo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_TipoVehiculo", nombreParameter, id_tipo_vehiculoParameter);
        }
    
        public virtual int sp_Modifica_Vehiculo(Nullable<int> id_vehiculo, Nullable<int> placa, Nullable<int> id_fabricante_vehiculo, Nullable<int> id_marca, Nullable<int> id_tipo_vehiculo, Nullable<int> id_modelo_vehiculo, Nullable<short> cantidad_puertas, Nullable<short> cantidad_ruedas, Nullable<System.DateTime> año_fabricacion)
        {
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            var placaParameter = placa.HasValue ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(int));
    
            var id_fabricante_vehiculoParameter = id_fabricante_vehiculo.HasValue ?
                new ObjectParameter("id_fabricante_vehiculo", id_fabricante_vehiculo) :
                new ObjectParameter("id_fabricante_vehiculo", typeof(int));
    
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            var id_modelo_vehiculoParameter = id_modelo_vehiculo.HasValue ?
                new ObjectParameter("id_modelo_vehiculo", id_modelo_vehiculo) :
                new ObjectParameter("id_modelo_vehiculo", typeof(int));
    
            var cantidad_puertasParameter = cantidad_puertas.HasValue ?
                new ObjectParameter("cantidad_puertas", cantidad_puertas) :
                new ObjectParameter("cantidad_puertas", typeof(short));
    
            var cantidad_ruedasParameter = cantidad_ruedas.HasValue ?
                new ObjectParameter("cantidad_ruedas", cantidad_ruedas) :
                new ObjectParameter("cantidad_ruedas", typeof(short));
    
            var año_fabricacionParameter = año_fabricacion.HasValue ?
                new ObjectParameter("año_fabricacion", año_fabricacion) :
                new ObjectParameter("año_fabricacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Vehiculo", id_vehiculoParameter, placaParameter, id_fabricante_vehiculoParameter, id_marcaParameter, id_tipo_vehiculoParameter, id_modelo_vehiculoParameter, cantidad_puertasParameter, cantidad_ruedasParameter, año_fabricacionParameter);
        }
    
        public virtual int sp_Modifica_Vehiculos_x_Cliente(Nullable<int> id_vehiculo, Nullable<int> id_cliente, Nullable<int> id_vehiculo_cliente)
        {
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_vehiculo_clienteParameter = id_vehiculo_cliente.HasValue ?
                new ObjectParameter("id_vehiculo_cliente", id_vehiculo_cliente) :
                new ObjectParameter("id_vehiculo_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Vehiculos_x_Cliente", id_vehiculoParameter, id_clienteParameter, id_vehiculo_clienteParameter);
        }
    
        public virtual int sp_ModificaCanton(Nullable<int> id_Canton, Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCanton", id_CantonParameter, id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_ModificaCliente(Nullable<int> id_cliente, string nombre, string apellido1, string apellido2, Nullable<int> cedula, Nullable<int> id_provincia, Nullable<int> id_canton, Nullable<int> id_distrito, string direccion, Nullable<int> telefono, string email)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCliente", id_clienteParameter, nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter, id_provinciaParameter, id_cantonParameter, id_distritoParameter, direccionParameter, telefonoParameter, emailParameter);
        }
    
        public virtual int sp_ModificaMarca(Nullable<int> id_marca, string nombre_marca, Nullable<int> id_fabricante)
        {
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            var nombre_marcaParameter = nombre_marca != null ?
                new ObjectParameter("nombre_marca", nombre_marca) :
                new ObjectParameter("nombre_marca", typeof(string));
    
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaMarca", id_marcaParameter, nombre_marcaParameter, id_fabricanteParameter);
        }
    
        public virtual int sp_ModificaModelo(Nullable<int> id_modelo, string nombre_modelo, Nullable<int> id_marca_modelo)
        {
            var id_modeloParameter = id_modelo.HasValue ?
                new ObjectParameter("id_modelo", id_modelo) :
                new ObjectParameter("id_modelo", typeof(int));
    
            var nombre_modeloParameter = nombre_modelo != null ?
                new ObjectParameter("nombre_modelo", nombre_modelo) :
                new ObjectParameter("nombre_modelo", typeof(string));
    
            var id_marca_modeloParameter = id_marca_modelo.HasValue ?
                new ObjectParameter("id_marca_modelo", id_marca_modelo) :
                new ObjectParameter("id_marca_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaModelo", id_modeloParameter, nombre_modeloParameter, id_marca_modeloParameter);
        }
    
        public virtual int sp_ModificaPais(Nullable<int> id_pais, string nombre)
        {
            var id_paisParameter = id_pais.HasValue ?
                new ObjectParameter("id_pais", id_pais) :
                new ObjectParameter("id_pais", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaPais", id_paisParameter, nombreParameter);
        }
    
        public virtual ObjectResult<sp_MostrarCliente_Result> sp_MostrarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MostrarCliente_Result>("sp_MostrarCliente");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_Retorna_cierre_Caja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_Retorna_cierre_Caja");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_Retorna_Fecha_Apertura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_Retorna_Fecha_Apertura");
        }
    
        public virtual ObjectResult<sp_retorna_parametro_Result> sp_retorna_parametro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retorna_parametro_Result>("sp_retorna_parametro");
        }
    
        public virtual ObjectResult<sp_retorna_tiposervicio_Result> sp_retorna_tiposervicio(Nullable<int> id_servicio)
        {
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retorna_tiposervicio_Result>("sp_retorna_tiposervicio", id_servicioParameter);
        }
    
        public virtual ObjectResult<sp_retorna_TODOS_tiposervicios_Result> sp_retorna_TODOS_tiposervicios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retorna_TODOS_tiposervicios_Result>("sp_retorna_TODOS_tiposervicios");
        }
    
        public virtual ObjectResult<sp_Retorna_Vehiculos_sin_Cliente_Result> sp_Retorna_Vehiculos_sin_Cliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Vehiculos_sin_Cliente_Result>("sp_Retorna_Vehiculos_sin_Cliente");
        }
    
        public virtual ObjectResult<sp_RetornaCantonesID_Result> sp_RetornaCantonesID(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCantonesID_Result>("sp_RetornaCantonesID", id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCliente_Result> sp_RetornaCliente(string nombre, string apellido1, string apellido2, Nullable<int> cedula, Nullable<int> id_provincia, Nullable<int> id_canton, Nullable<int> id_distrito, string direccion, Nullable<int> telefono, string email)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCliente_Result>("sp_RetornaCliente", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter, id_provinciaParameter, id_cantonParameter, id_distritoParameter, direccionParameter, telefonoParameter, emailParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCliente_ID_Result> sp_RetornaCliente_ID(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("Id_cliente", id_cliente) :
                new ObjectParameter("Id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCliente_ID_Result>("sp_RetornaCliente_ID", id_clienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_Result> sp_RetornaDistritos(string nombre, Nullable<int> id_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_Result>("sp_RetornaDistritos", nombreParameter, id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_ID_Result> sp_RetornaDistritos_ID(Nullable<int> id_Distrito)
        {
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_ID_Result>("sp_RetornaDistritos_ID", id_DistritoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaFabricante_ID_Result> sp_RetornaFabricante_ID(Nullable<int> id_fabricante)
        {
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaFabricante_ID_Result>("sp_RetornaFabricante_ID", id_fabricanteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaFabricantes_Result> sp_RetornaFabricantes(Nullable<int> id_fabricante, string nombrefabr, Nullable<int> pais)
        {
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            var nombrefabrParameter = nombrefabr != null ?
                new ObjectParameter("nombrefabr", nombrefabr) :
                new ObjectParameter("nombrefabr", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaFabricantes_Result>("sp_RetornaFabricantes", id_fabricanteParameter, nombrefabrParameter, paisParameter);
        }
    
        public virtual ObjectResult<sp_RetornaFacturaEncabezadoID_Result> sp_RetornaFacturaEncabezadoID(Nullable<int> id_factura)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaFacturaEncabezadoID_Result>("sp_RetornaFacturaEncabezadoID", id_facturaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaFacturas_Result> sp_RetornaFacturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaFacturas_Result>("sp_RetornaFacturas");
        }
    
        public virtual ObjectResult<sp_RetornaListaMarca_Result> sp_RetornaListaMarca(Nullable<int> id_marca, string nombre_marca, Nullable<int> id_fabricante)
        {
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            var nombre_marcaParameter = nombre_marca != null ?
                new ObjectParameter("nombre_marca", nombre_marca) :
                new ObjectParameter("nombre_marca", typeof(string));
    
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaListaMarca_Result>("sp_RetornaListaMarca", id_marcaParameter, nombre_marcaParameter, id_fabricanteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMarca_ID_Result> sp_RetornaMarca_ID(Nullable<int> id_marca)
        {
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMarca_ID_Result>("sp_RetornaMarca_ID", id_marcaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaModelo_Result> sp_RetornaModelo(string nombre_modelo, Nullable<int> id_fabricante, Nullable<int> id_marca)
        {
            var nombre_modeloParameter = nombre_modelo != null ?
                new ObjectParameter("nombre_modelo", nombre_modelo) :
                new ObjectParameter("nombre_modelo", typeof(string));
    
            var id_fabricanteParameter = id_fabricante.HasValue ?
                new ObjectParameter("id_fabricante", id_fabricante) :
                new ObjectParameter("id_fabricante", typeof(int));
    
            var id_marcaParameter = id_marca.HasValue ?
                new ObjectParameter("id_marca", id_marca) :
                new ObjectParameter("id_marca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaModelo_Result>("sp_RetornaModelo", nombre_modeloParameter, id_fabricanteParameter, id_marcaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaModelo_ID_Result> sp_RetornaModelo_ID(Nullable<int> id_modelo)
        {
            var id_modeloParameter = id_modelo.HasValue ?
                new ObjectParameter("id_modelo", id_modelo) :
                new ObjectParameter("id_modelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaModelo_ID_Result>("sp_RetornaModelo_ID", id_modeloParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPais_Result> sp_RetornaPais(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPais_Result>("sp_RetornaPais", nombreParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPais_ID_Result> sp_RetornaPais_ID(Nullable<int> id_pais)
        {
            var id_paisParameter = id_pais.HasValue ?
                new ObjectParameter("id_pais", id_pais) :
                new ObjectParameter("id_pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPais_ID_Result>("sp_RetornaPais_ID", id_paisParameter);
        }
    
        public virtual ObjectResult<sp_RetornaProvincias_Result> sp_RetornaProvincias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaProvincias_Result>("sp_RetornaProvincias", nombreParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTipoServicio_ID_Result> sp_RetornaTipoServicio_ID(Nullable<int> id_tipo_servicio)
        {
            var id_tipo_servicioParameter = id_tipo_servicio.HasValue ?
                new ObjectParameter("id_tipo_servicio", id_tipo_servicio) :
                new ObjectParameter("id_tipo_servicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTipoServicio_ID_Result>("sp_RetornaTipoServicio_ID", id_tipo_servicioParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTipoVehiculo_Result> sp_RetornaTipoVehiculo(Nullable<int> id_tipo_vehiculo, string nombre_vehiculo)
        {
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            var nombre_vehiculoParameter = nombre_vehiculo != null ?
                new ObjectParameter("nombre_vehiculo", nombre_vehiculo) :
                new ObjectParameter("nombre_vehiculo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTipoVehiculo_Result>("sp_RetornaTipoVehiculo", id_tipo_vehiculoParameter, nombre_vehiculoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTipoVehiculo_ID_Result> sp_RetornaTipoVehiculo_ID(Nullable<int> id_tipo_vehiculo)
        {
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTipoVehiculo_ID_Result>("sp_RetornaTipoVehiculo_ID", id_tipo_vehiculoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaVehiculo_Result> sp_RetornaVehiculo(Nullable<int> id_vehiculo)
        {
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaVehiculo_Result>("sp_RetornaVehiculo", id_vehiculoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaVehiculo_ID_Result> sp_RetornaVehiculo_ID(Nullable<int> id_vehiculo)
        {
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaVehiculo_ID_Result>("sp_RetornaVehiculo_ID", id_vehiculoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaVehiculosxCliente_Result> sp_RetornaVehiculosxCliente(Nullable<int> id_vehiculo_cliente, Nullable<int> id_cliente, Nullable<int> id_vehiculo)
        {
            var id_vehiculo_clienteParameter = id_vehiculo_cliente.HasValue ?
                new ObjectParameter("id_vehiculo_cliente", id_vehiculo_cliente) :
                new ObjectParameter("id_vehiculo_cliente", typeof(int));
    
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_vehiculoParameter = id_vehiculo.HasValue ?
                new ObjectParameter("id_vehiculo", id_vehiculo) :
                new ObjectParameter("id_vehiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaVehiculosxCliente_Result>("sp_RetornaVehiculosxCliente", id_vehiculo_clienteParameter, id_clienteParameter, id_vehiculoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaVehiculosxClientebyIdCliente_Result> sp_RetornaVehiculosxClientebyIdCliente(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaVehiculosxClientebyIdCliente_Result>("sp_RetornaVehiculosxClientebyIdCliente", id_clienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaVehiculoxCliente_ID_Result> sp_RetornaVehiculoxCliente_ID(Nullable<int> id_vehiculo_cliente)
        {
            var id_vehiculo_clienteParameter = id_vehiculo_cliente.HasValue ?
                new ObjectParameter("id_vehiculo_cliente", id_vehiculo_cliente) :
                new ObjectParameter("id_vehiculo_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaVehiculoxCliente_ID_Result>("sp_RetornaVehiculoxCliente_ID", id_vehiculo_clienteParameter);
        }
    
        public virtual ObjectResult<sp_UltimaCaja_Result> sp_UltimaCaja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UltimaCaja_Result>("sp_UltimaCaja");
        }
    
        public virtual int sp_update_parametro(string nombre, string correo_aperture, string correo_cierre, Nullable<double> monto_minimo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correo_apertureParameter = correo_aperture != null ?
                new ObjectParameter("correo_aperture", correo_aperture) :
                new ObjectParameter("correo_aperture", typeof(string));
    
            var correo_cierreParameter = correo_cierre != null ?
                new ObjectParameter("correo_cierre", correo_cierre) :
                new ObjectParameter("correo_cierre", typeof(string));
    
            var monto_minimoParameter = monto_minimo.HasValue ?
                new ObjectParameter("monto_minimo", monto_minimo) :
                new ObjectParameter("monto_minimo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_parametro", nombreParameter, correo_apertureParameter, correo_cierreParameter, monto_minimoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Veficia_Placa_Existente(Nullable<int> placa)
        {
            var placaParameter = placa.HasValue ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Veficia_Placa_Existente", placaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Verifica_Cliente_Existente(Nullable<int> cedula)
        {
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Verifica_Cliente_Existente", cedulaParameter);
        }
    }
}
