//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marca_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public marca_vehiculo()
        {
            this.modelo_vehiculo = new HashSet<modelo_vehiculo>();
        }
    
        public int id_marca { get; set; }
        public string nombre_marca { get; set; }
        public Nullable<int> id_fabricante { get; set; }
    
        public virtual fabricante fabricante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelo_vehiculo> modelo_vehiculo { get; set; }
    }
}
