//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo_vehículo
    {
        public int cod_modelo { get; set; }
        public string nombre_modelo { get; set; }
        public int cod_marca_modelo { get; set; }
    
        public virtual marca_vehículo marca_vehículo { get; set; }
    }
}
