//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos_x_cliente
    {
        public int id_vehiculo_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public int id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
