//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculo()
        {
            this.factura_encabezado = new HashSet<factura_encabezado>();
            this.vehiculos_x_cliente = new HashSet<vehiculos_x_cliente>();
        }
    
        public int id_vehiculo { get; set; }
        public int placa { get; set; }
        public int id_marca { get; set; }
        public int id_tipo_vehiculo { get; set; }
        public int id_modelo_vehiculo { get; set; }
        public short cantidad_puertas { get; set; }
        public short cantidad_ruedas { get; set; }
        public System.DateTime año_fabricacion { get; set; }
        public int id_fabricante_vehiculo { get; set; }
    
        public virtual fabricante fabricante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_encabezado> factura_encabezado { get; set; }
        public virtual tipo_vehiculo tipo_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiculos_x_cliente> vehiculos_x_cliente { get; set; }
    }
}
