//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos_x_cliente
    {
        public int id_vehiculo_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public int id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
