//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaCarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehículos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehículos()
        {
            this.vehículos_x_cliente = new HashSet<vehículos_x_cliente>();
        }
    
        public int id_vehículo { get; set; }
        public int placa { get; set; }
        public int id_marca { get; set; }
        public int id_tipo_vehículo { get; set; }
        public int id_modelo_vehículo { get; set; }
        public short cantidad_puertas { get; set; }
        public short cantidad_ruedas { get; set; }
        public System.DateTime año_fabricación { get; set; }
        public int cod_fabricante_vehículo { get; set; }
    
        public virtual fabricante fabricante { get; set; }
        public virtual marca_vehículo marca_vehículo { get; set; }
        public virtual tipo_vehículo tipo_vehículo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehículos_x_cliente> vehículos_x_cliente { get; set; }
    }
}
